---
title: "Chicago Divvy"
author: "Keith Hultman"
date: "April 22, 2017"
output: html_notebook
---

Let's explore some Divvy bike data from Chicago.

```{r, message=FALSE, warning=FALSE}
library(tidyverse)
library(lubridate)
library(forecast)
```

```{r}
divvy <- read_csv("data/divvy_daily_duration.csv")

divvy$date <- mdy(divvy$`START TIME`)
divvy$`START TIME` <- NULL
divvy$duration <- divvy$`TRIP DURATION`
divvy$`TRIP DURATION` <- NULL

divvy2 <- divvy %>% group_by(week = as.POSIXct(cut(date, "week"))) %>% summarise(weekly_rides = sum(duration))

#decompose(divvy2, type = "additive")
```



```{r}
library(xts)

divvy_ts <- xts(divvy2$weekly_rides, order.by = divvy2$week)

divvy_ts2 <- ts(divvy_ts, start = c(2013, 25), frequency = 52)
autoplot(divvy_ts2)
ggseasonplot(divvy_ts2)
autoplot(decompose(divvy_ts2))
```

Try damped ETS

```{r}
fit1 <- ets(divvy_ts2, damped = TRUE)
autoplot(fit1)
autoplot(forecast(fit1, h = 7))
```


```{r}
fit2 <- hw(divvy_ts2, seasonal = "multiplicative", h = 7)

```

Try monthly data

```{r}
divvy <- read_csv("data/divvy_monthly.csv")

divvy$date <- mdy_hms(divvy$`START TIME`)

divvy$`START TIME` <- NULL
divvy$duration <- divvy$`TRIP DURATION`
divvy$`TRIP DURATION` <- NULL

divvy <- divvy %>% filter(date > "2014-01-01")
divvy_ts <- xts(divvy$duration, order.by = divvy$date)
divvy_ts <- ts(divvy_ts, start = c(2013, 6), frequency = 12)
autoplot(divvy_ts)
```




Try some other methods on weekly data. Let's try seasonal naive

```{r}
fit3 <- snaive(divvy_ts2, h=7, lambda = 0)
autoplot(forecast(fit3))
```
```{r}
fit4 <- stlm(divvy_ts2, method = "ets", lambda = 0)
```

